alter table if exists public.tasks
  add column if not exists user_id uuid references auth.users(id) on delete cascade;

alter table public.tasks enable row level security;

drop policy if exists "Allow public read access to tasks" on public.tasks;
drop policy if exists "Allow public insert access to tasks" on public.tasks;
drop policy if exists "Allow public update access to tasks" on public.tasks;
drop policy if exists "Allow public delete access to tasks" on public.tasks;

create policy if not exists "Users can view their own tasks"
  on public.tasks
  for select
  using (auth.uid() = user_id);

create policy if not exists "Users can insert their own tasks"
  on public.tasks
  for insert
  with check (auth.uid() = user_id);

create policy if not exists "Users can update their own tasks"
  on public.tasks
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy if not exists "Users can delete their own tasks"
  on public.tasks
  for delete
  using (auth.uid() = user_id);

create table if not exists public.livestock_records (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  tag_number text not null,
  name text not null,
  breed text,
  birth_date date,
  sex text,
  weight numeric(10,2),
  status text,
  notes text,
  photo_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint livestock_records_user_tag_unique unique (user_id, tag_number)
);

alter table if exists public.livestock_records
  add column if not exists photo_url text;

alter table public.livestock_records enable row level security;

drop policy if exists "Users can view their own livestock records" on public.livestock_records;
drop policy if exists "Users can insert their own livestock records" on public.livestock_records;
drop policy if exists "Users can update their own livestock records" on public.livestock_records;
drop policy if exists "Users can delete their own livestock records" on public.livestock_records;

create policy "Users can view their own livestock records"
  on public.livestock_records
  for select
  using (auth.uid() = user_id);

create policy "Users can insert their own livestock records"
  on public.livestock_records
  for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own livestock records"
  on public.livestock_records
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Users can delete their own livestock records"
  on public.livestock_records
  for delete
  using (auth.uid() = user_id);
