alter table if exists public.tasks
  add column if not exists user_id uuid references auth.users(id) on delete cascade;

alter table public.tasks enable row level security;

drop policy if exists "Allow public read access to tasks" on public.tasks;
drop policy if exists "Allow public insert access to tasks" on public.tasks;
drop policy if exists "Allow public update access to tasks" on public.tasks;
drop policy if exists "Allow public delete access to tasks" on public.tasks;

create policy if not exists "Users can view their own tasks"
  on public.tasks
  for select
  using (auth.uid() = user_id);

create policy if not exists "Users can insert their own tasks"
  on public.tasks
  for insert
  with check (auth.uid() = user_id);

create policy if not exists "Users can update their own tasks"
  on public.tasks
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy if not exists "Users can delete their own tasks"
  on public.tasks
  for delete
  using (auth.uid() = user_id);

create table if not exists public.livestock_records (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  tag_number text not null,
  name text not null,
  breed text,
  birth_date date,
  sex text,
  weight numeric(10,2),
  status text,
  notes text,
  photo_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint livestock_records_user_tag_unique unique (user_id, tag_number)
);

alter table if exists public.livestock_records
  add column if not exists photo_url text;

alter table public.livestock_records enable row level security;

drop policy if exists "Users can view their own livestock records" on public.livestock_records;
drop policy if exists "Users can insert their own livestock records" on public.livestock_records;
drop policy if exists "Users can update their own livestock records" on public.livestock_records;
drop policy if exists "Users can delete their own livestock records" on public.livestock_records;

create policy "Users can view their own livestock records"
  on public.livestock_records
  for select
  using (auth.uid() = user_id);

create policy "Users can insert their own livestock records"
  on public.livestock_records
  for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own livestock records"
  on public.livestock_records
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Users can delete their own livestock records"
  on public.livestock_records
  for delete
  using (auth.uid() = user_id);

create table if not exists public.equipment_records (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  type text,
  make text,
  model text,
  year integer,
  serial_number text,
  status text not null default 'Active',
  purchase_date date,
  purchase_price numeric(12,2),
  current_usage text,
  last_service_date date,
  next_service_date date,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.equipment_records enable row level security;

drop policy if exists "Users can view their own equipment records" on public.equipment_records;
drop policy if exists "Users can insert their own equipment records" on public.equipment_records;
drop policy if exists "Users can update their own equipment records" on public.equipment_records;
drop policy if exists "Users can delete their own equipment records" on public.equipment_records;

create policy "Users can view their own equipment records"
  on public.equipment_records
  for select
  using (auth.uid() = user_id);

create policy "Users can insert their own equipment records"
  on public.equipment_records
  for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own equipment records"
  on public.equipment_records
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Users can delete their own equipment records"
  on public.equipment_records
  for delete
  using (auth.uid() = user_id);

create table if not exists public.pasture_records (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  acres numeric(10,2),
  gps_location text,
  grass_type text,
  water_source text,
  fence_condition text,
  carrying_capacity integer,
  current_herd integer,
  last_grazed date,
  rest_until_date date,
  notes text,
  photo_urls text[],
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.pasture_records enable row level security;

drop policy if exists "Users can view their own pasture records" on public.pasture_records;
drop policy if exists "Users can insert their own pasture records" on public.pasture_records;
drop policy if exists "Users can update their own pasture records" on public.pasture_records;
drop policy if exists "Users can delete their own pasture records" on public.pasture_records;

create policy "Users can view their own pasture records"
  on public.pasture_records
  for select
  using (auth.uid() = user_id);

create policy "Users can insert their own pasture records"
  on public.pasture_records
  for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own pasture records"
  on public.pasture_records
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Users can delete their own pasture records"
  on public.pasture_records
  for delete
  using (auth.uid() = user_id);

create table if not exists public.finance_transactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  date date not null,
  transaction_type text not null check (transaction_type in ('income', 'expense')),
  category text not null,
  description text not null,
  amount numeric(12,2) not null check (amount >= 0),
  business text not null,
  payment_method text,
  notes text,
  receipt_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.finance_transactions enable row level security;

drop policy if exists "Users can view their own finance transactions" on public.finance_transactions;
drop policy if exists "Users can insert their own finance transactions" on public.finance_transactions;
drop policy if exists "Users can update their own finance transactions" on public.finance_transactions;
drop policy if exists "Users can delete their own finance transactions" on public.finance_transactions;

create policy "Users can view their own finance transactions"
  on public.finance_transactions
  for select
  using (auth.uid() = user_id);

create policy "Users can insert their own finance transactions"
  on public.finance_transactions
  for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own finance transactions"
  on public.finance_transactions
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Users can delete their own finance transactions"
  on public.finance_transactions
  for delete
  using (auth.uid() = user_id);

insert into storage.buckets (id, name, public)
values ('finance-receipts', 'finance-receipts', true)
on conflict (id) do nothing;

drop policy if exists "Users can upload their own finance receipts" on storage.objects;
drop policy if exists "Users can update their own finance receipts" on storage.objects;
drop policy if exists "Users can delete their own finance receipts" on storage.objects;
drop policy if exists "Public can view finance receipts" on storage.objects;

create policy "Users can upload their own finance receipts"
  on storage.objects
  for insert
  to authenticated
  with check (
    bucket_id = 'finance-receipts'
    and split_part(name, '/', 1) = auth.uid()::text
  );

create policy "Users can update their own finance receipts"
  on storage.objects
  for update
  to authenticated
  using (
    bucket_id = 'finance-receipts'
    and split_part(name, '/', 1) = auth.uid()::text
  )
  with check (
    bucket_id = 'finance-receipts'
    and split_part(name, '/', 1) = auth.uid()::text
  );

create policy "Users can delete their own finance receipts"
  on storage.objects
  for delete
  to authenticated
  using (
    bucket_id = 'finance-receipts'
    and split_part(name, '/', 1) = auth.uid()::text
  );

create policy "Public can view finance receipts"
  on storage.objects
  for select
  to public
  using (bucket_id = 'finance-receipts');

create table if not exists public.companion_memories (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  category text not null check (
    category in (
      'Preferences',
      'Goals',
      'Businesses',
      'Farm and Ranch',
      'Writing',
      'People',
      'Projects',
      'Important Facts'
    )
  ),
  content text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.companion_memories enable row level security;

drop policy if exists "Users can view their own companion memories" on public.companion_memories;
drop policy if exists "Users can insert their own companion memories" on public.companion_memories;
drop policy if exists "Users can update their own companion memories" on public.companion_memories;
drop policy if exists "Users can delete their own companion memories" on public.companion_memories;

create policy "Users can view their own companion memories"
  on public.companion_memories
  for select
  using (auth.uid() = user_id);

create policy "Users can insert their own companion memories"
  on public.companion_memories
  for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own companion memories"
  on public.companion_memories
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Users can delete their own companion memories"
  on public.companion_memories
  for delete
  using (auth.uid() = user_id);

create table if not exists public.companion_messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null check (role in ('user', 'assistant', 'system')),
  content text not null,
  created_at timestamptz not null default now()
);

alter table public.companion_messages enable row level security;

drop policy if exists "Users can view their own companion messages" on public.companion_messages;
drop policy if exists "Users can insert their own companion messages" on public.companion_messages;
drop policy if exists "Users can delete their own companion messages" on public.companion_messages;

create policy "Users can view their own companion messages"
  on public.companion_messages
  for select
  using (auth.uid() = user_id);

create policy "Users can insert their own companion messages"
  on public.companion_messages
  for insert
  with check (auth.uid() = user_id);

create policy "Users can delete their own companion messages"
  on public.companion_messages
  for delete
  using (auth.uid() = user_id);

create table if not exists public.companion_settings (
  user_id uuid primary key references auth.users(id) on delete cascade,
  memory_enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.companion_settings enable row level security;

drop policy if exists "Users can view their own companion settings" on public.companion_settings;
drop policy if exists "Users can insert their own companion settings" on public.companion_settings;
drop policy if exists "Users can update their own companion settings" on public.companion_settings;

create policy "Users can view their own companion settings"
  on public.companion_settings
  for select
  using (auth.uid() = user_id);

create policy "Users can insert their own companion settings"
  on public.companion_settings
  for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own companion settings"
  on public.companion_settings
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create table if not exists public.companion_ai_settings (
  user_id uuid primary key references auth.users(id) on delete cascade,
  preferred_mode text not null default 'local' check (preferred_mode in ('local', 'cloud')),
  provider text not null default 'openai' check (provider in ('openai', 'anthropic')),
  model text not null default 'gpt-4o-mini',
  monthly_usage_cap_tokens integer not null default 200000 check (monthly_usage_cap_tokens > 0),
  spending_limit_usd numeric(10,2) not null default 15 check (spending_limit_usd > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.companion_ai_settings enable row level security;

drop policy if exists "Users can view their own companion ai settings" on public.companion_ai_settings;
drop policy if exists "Users can insert their own companion ai settings" on public.companion_ai_settings;
drop policy if exists "Users can update their own companion ai settings" on public.companion_ai_settings;

create policy "Users can view their own companion ai settings"
  on public.companion_ai_settings
  for select
  using (auth.uid() = user_id);

create policy "Users can insert their own companion ai settings"
  on public.companion_ai_settings
  for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own companion ai settings"
  on public.companion_ai_settings
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create table if not exists public.companion_ai_usage (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  provider text not null,
  model text not null,
  estimated_tokens integer not null default 0,
  estimated_cost_usd numeric(12,6) not null default 0,
  created_at timestamptz not null default now()
);

alter table public.companion_ai_usage enable row level security;

drop policy if exists "Users can view their own companion ai usage" on public.companion_ai_usage;
drop policy if exists "Users can insert their own companion ai usage" on public.companion_ai_usage;

create policy "Users can view their own companion ai usage"
  on public.companion_ai_usage
  for select
  using (auth.uid() = user_id);

create policy "Users can insert their own companion ai usage"
  on public.companion_ai_usage
  for insert
  with check (auth.uid() = user_id);

create table if not exists public.daily_briefings (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  top_priorities text[] not null default '{}'::text[],
  important_alerts text[] not null default '{}'::text[],
  financial_snapshot text not null default '',
  ranch_status text not null default '',
  ai_employee_status text not null default '',
  recommended_next_action text not null default '',
  summary_text text not null default '',
  spoken_text text not null default '',
  source_mode text not null default 'local',
  source_provider text not null default 'local-free',
  source_model text not null default 'template-v1',
  cloud_active boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.daily_briefings enable row level security;

drop policy if exists "Users can view their own daily briefings" on public.daily_briefings;
drop policy if exists "Users can insert their own daily briefings" on public.daily_briefings;
drop policy if exists "Users can delete their own daily briefings" on public.daily_briefings;

create policy "Users can view their own daily briefings"
  on public.daily_briefings
  for select
  using (auth.uid() = user_id);

create policy "Users can insert their own daily briefings"
  on public.daily_briefings
  for insert
  with check (auth.uid() = user_id);

create policy "Users can delete their own daily briefings"
  on public.daily_briefings
  for delete
  using (auth.uid() = user_id);
