-- Founding Farmer core: additive tables only. Existing ranch, finance, storage, and commerce data are untouched.

create table if not exists public.farm_profiles (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  operation_name text not null,
  operation_type text not null default 'Farm & Ranch',
  county_state text,
  production_focus text,
  certification_status text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id)
);

create table if not exists public.farm_fields (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  land_type text not null default 'Field' check (land_type in ('Field','Pasture')),
  tenure text not null default 'Owned' check (tenure in ('Owned','Rented')),
  acres numeric(12,2) not null check (acres > 0),
  landlord text,
  legal_description text,
  crop_name text,
  production_type text not null default 'Conventional',
  crop_year integer not null default extract(year from current_date)::integer,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.farm_applications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  field_id bigint not null references public.farm_fields(id) on delete cascade,
  applied_on date not null,
  category text not null,
  product_name text not null,
  rate numeric(12,3),
  rate_unit text,
  method text,
  weather text,
  total_cost numeric(12,2) not null default 0 check (total_cost >= 0),
  label_source text,
  notes text,
  created_at timestamptz not null default now()
);

create table if not exists public.farm_harvests (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  field_id bigint not null references public.farm_fields(id) on delete cascade,
  harvested_on date not null,
  crop_year integer not null,
  total_weight_lbs numeric(14,2) not null default 0 check (total_weight_lbs >= 0),
  total_bushels numeric(14,2) not null default 0 check (total_bushels >= 0),
  harvested_acres numeric(12,2) check (harvested_acres > 0),
  revenue numeric(14,2) not null default 0 check (revenue >= 0),
  quality_grade text,
  notes text,
  created_at timestamptz not null default now()
);

create table if not exists public.farm_costs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  field_id bigint references public.farm_fields(id) on delete set null,
  incurred_on date not null,
  category text not null,
  description text not null,
  amount numeric(14,2) not null check (amount >= 0),
  notes text,
  created_at timestamptz not null default now()
);

create table if not exists public.livestock_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  livestock_id bigint references public.livestock_records(id) on delete set null,
  event_date date not null,
  event_type text not null check (event_type in ('Feed','Treatment','Breeding','Movement')),
  description text not null,
  quantity numeric(12,3),
  unit text,
  cost numeric(14,2) not null default 0 check (cost >= 0),
  withdrawal_until date,
  from_location text,
  to_location text,
  notes text,
  created_at timestamptz not null default now()
);

alter table public.farm_profiles enable row level security;
alter table public.farm_fields enable row level security;
alter table public.farm_applications enable row level security;
alter table public.farm_harvests enable row level security;
alter table public.farm_costs enable row level security;
alter table public.livestock_events enable row level security;

revoke all on table public.farm_profiles, public.farm_fields, public.farm_applications, public.farm_harvests, public.farm_costs, public.livestock_events from anon;
grant select, insert, update, delete on table public.farm_profiles, public.farm_fields, public.farm_applications, public.farm_harvests, public.farm_costs, public.livestock_events to authenticated;
grant usage, select on all sequences in schema public to authenticated;

do $$
declare t text;
begin
  foreach t in array array['farm_profiles','farm_fields','farm_applications','farm_harvests','farm_costs','livestock_events']
  loop
    execute format('drop policy if exists %I on public.%I', t || '_select_own', t);
    execute format('drop policy if exists %I on public.%I', t || '_insert_own', t);
    execute format('drop policy if exists %I on public.%I', t || '_update_own', t);
    execute format('drop policy if exists %I on public.%I', t || '_delete_own', t);
    execute format('create policy %I on public.%I for select to authenticated using ((select auth.uid()) = user_id)', t || '_select_own', t);
    execute format('create policy %I on public.%I for insert to authenticated with check ((select auth.uid()) = user_id)', t || '_insert_own', t);
    execute format('create policy %I on public.%I for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id)', t || '_update_own', t);
    execute format('create policy %I on public.%I for delete to authenticated using ((select auth.uid()) = user_id)', t || '_delete_own', t);
  end loop;
end $$;

create index if not exists farm_fields_user_id_idx on public.farm_fields(user_id);
create index if not exists farm_fields_user_year_idx on public.farm_fields(user_id, crop_year);
create index if not exists farm_applications_user_id_idx on public.farm_applications(user_id);
create index if not exists farm_applications_field_id_idx on public.farm_applications(field_id);
create index if not exists farm_harvests_user_year_idx on public.farm_harvests(user_id, crop_year);
create index if not exists farm_harvests_field_id_idx on public.farm_harvests(field_id);
create index if not exists farm_costs_user_date_idx on public.farm_costs(user_id, incurred_on);
create index if not exists farm_costs_field_id_idx on public.farm_costs(field_id);
create index if not exists livestock_events_user_date_idx on public.livestock_events(user_id, event_date);
create index if not exists livestock_events_livestock_id_idx on public.livestock_events(livestock_id);
